### ISSUE TITLE
Uninstall does not remove /usr/local/share/gem_home

### ISSUE THREAD

**Issue by krisleech** [postmodern/gem_home#14]
It removes the contents, but not the directory itself.

![22500](https://cloud.githubusercontent.com/assets/66143/23209536/7f57b1a4-f8f1-11e6-8714-2437983658bb.png)

**Comment by krisleech** [comment]
I've never worked on a Makefile before, so there might be better ways, but here is a PR to demonstrate a fix: https://github.com/postmodern/gem_home/pull/15

**Comment by postmodern** [comment]
This appears to be an issue with the `find` command. What does `find etc lib bin sbin share -type f 2>/dev/null` output in your environment?

**Comment by postmodern** [comment]
Derp now I see. Merged!
