### ISSUE TITLE
Homebrew instructions no longer correct

### ISSUE THREAD

**Issue by calebthompson** [postmodern/gem_home#19]
Homebrew seems to have made some change that disallows the method by which we're meant to install gem_home with `brew`:

```
Error: Calling Non-checksummed download of gem_home formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/postmodern/gem_home/issues/new
```

**Comment by postmodern** [comment]
Ah looks like they've changed how to install formulas from github: https://dev.to/gjrdiesel/getting-around-brew-s-error-calling-non-checksummed-download-of-17fl

**Comment by mfilej** [comment]
This makes it harder to have `gem_home` as part of a Brewfile bundle. If anyone knows a workaround I'd be interested.
