### ISSUE TITLE
Support gemsets

### ISSUE THREAD

**Issue by postmodern** [postmodern/gem_home#3]
Support setting `GEM_HOME` to `$HOME/.gem/$gemset`.

**Comment by franklinyu** [comment]
Isn't the issue better handled by Bundler?

**Comment by postmodern** [comment]
Closing this. Bundler has replaced gemsets. Plus now there's [chgems](https://github.com/postmodern/chgems#readme) for when you need to manipulate `$GEM_PATH`.

**Comment by habibalamin** [comment]
@postmodern `chgems` is deprecated in favour of `gem_home`. I don't understand what the difference is between the two projects. It seems like the only substantial difference is that `gem_home` plays nicely with RVM and `chruby`, while `chgems` plays nicely with `chruby`, `rbenv` and `rbfu`. I don't understand what the purpose of deprecating `chgems` was.

**Comment by postmodern** [comment]
@habibalamin `chgems` spawned a new sub-shell when switching to a "gemset", which could cause confusion if the user forgets to exit the sub-shell. `gem_home` simply modifies `GEM_HOME`/`GEM_PATH` in a similar way to how `pushd`/`popd` works in Bash.

**Comment by habibalamin** [comment]
But why not just create a bugfix release of `chgems`?

**Comment by postmodern** [comment]
@habibalamin the changes were so significant it made more sense to create a new project. `chgems` was designed to be similar to `chroot` (thus the `ch`), where as `gem_home` just modifies `$GEM_HOME` and `$GEM_PATH`. I will eventually delete this repository.

**Comment by habibalamin** [comment]
Sorry, I'm kind of confused. You say:

>Plus now there's [chgems](https://github.com/postmodern/chgems#readme) for when you need to manipulate `$GEM_PATH`.

which implies that `chgems` replaces `gem_home` (and perhaps even that it came after `gem_home`), but the `chgems` README says:

>DEPRECATED: use [gem_home](https://github.com/postmodern/gem_home#readme) instead

But you corroborate that `chgems` replaces `gem_home` when you say in this `gem_home` issue:

>I will eventually delete this repository.

and say the reason for not creating a bugfix release of `chgems` is that:

>the changes were so significant it made more sense to create a new project.

Which deprecates which?

---

>`chgems` was designed to be similar to `chroot` (thus the `ch`)

Ah, I took the `ch` to be a signal that it's similar to (and designed to play well with) `chruby`, your other tool for managing Rubies.

While testing both programs now, it seems that `chgems` is useful for doing something like `bundle exec` (or `chroot`, as you say), whereas `gem_home` behaves more similarly to `chruby` in that it just sets environment variables (but is a bit different in that it allows pushing and popping, with `gem list` and the like reading from all the listed `.gems` directories, but `gem install` and the like writing to the topmost `.gems` of the stack).

Seems like `gem_home` is the one I want for my purposes most of the time (although `chgems` behaviour would certainly be useful at times); are you going to kill `gem_home`?

**Comment by postmodern** [comment]
Oops, I meant to say I will someday delete _chgems_ to avoid confusion.
