### ISSUE TITLE
Zsh pushd setopts interfere with gem_home_push()

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [postmodern/gem_home#7]
I've managed to track down issue that was bugging me when using gem_home - executing `gem_home .` would change current working directory.

The problem was due to Zsh `setopt`'s `auto_pushd` and `pushd_ignore_dups`. When both are set (as is case with popular Zsh framework [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/directories.zsh#L3-L4)) directory changes. Here's quick & dirty [testcase](https://github.com/aledovsky/gem_home-test)

As a workaround, I've added `unsetopt auto_pushd` and `unsetopt pushd_ignore_dups` in my `.zshrc`.

Maybe gem_home could detect such option combo for Zsh and warn appropriately?

**Comment by krisleech** [comment]
With the workround:

```
unsetopt auto_pushd
unsetopt pushd_ignore_dups
```

is good for me on Zsh 5.1.1.
